// Builds docs/ideas/INDEX.md: every extracted idea, grouped by strength, from docs/ideas/<slug>.md.
//   node scripts/ideas-index.mjs
import fs from "node:fs";
import path from "node:path";

const DIR = path.join(process.cwd(), "docs", "ideas");
const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".md") && f === f.toLowerCase());

const ideas = files.flatMap((f) => {
  const slug = f.replace(/\.md$/, "");
  return fs
    .readFileSync(path.join(DIR, f), "utf8")
    .split(/^## /m)
    .slice(1)
    .map((sec) => {
      const field = (k) => (sec.match(new RegExp(`\\*\\*${k}:\\*\\*\\s*(.*)`))?.[1] ?? "").trim();
      return {
        slug,
        name: sec.split("\n")[0].trim(),
        type: field("Type"),
        claim: field("Claim"),
        title: field("Micro-article").split(" · ")[0].replace(/^\*+|\*+$/g, ""),
        strength: Number(field("Strength").match(/\d/)?.[0] ?? 0),
      };
    });
});

const anchor = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const row = (i) => `| [${i.name}](${i.slug}.md#${anchor(i.name)}) | ${i.type} | \`${i.slug}\` | ${i.claim.replace(/\|/g, "/")} |`;

let md = `# Idea catalog

${ideas.length} ideas from ${files.length} essays. Generated by \`scripts/ideas-index.mjs\`; curated picks are in [README.md](README.md).

`;
for (const s of [3, 2, 1]) {
  const list = ideas.filter((i) => i.strength === s);
  md += `## Strength ${s} (${list.length})\n\n| Idea | Type | Essay | Claim |\n|---|---|---|---|\n${list.map(row).join("\n")}\n\n`;
}
fs.writeFileSync(path.join(DIR, "INDEX.md"), md);
console.log(`${ideas.length} ideas → docs/ideas/INDEX.md`);
for (const i of ideas.filter((i) => i.strength === 3)) console.log(`[${i.slug}] ${i.name} :: ${i.title}`);
